version: "3.1"
services:
    webserver:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-webserver
        working_dir: /application
        networks:
            - internal
        volumes:
            - ./../:/application
            - ./sourcefiles/nginx:/etc/nginx/conf.d
        ports:
            - "${NGINX_PORT}:80"

    php-fpm:
        build: sourcefiles/php-fpm
        container_name: ${PROJECT_NAME}-php-fpm
        working_dir: /application
        environment:
            - PHP_WORKER_INSTALL_BCMATH=true
        volumes:
            - ./../:/application
            - ./sourcefiles/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./sourcefiles/php-fpm/conf.d/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
        networks:
            - internal

networks:
    internal:
        driver: bridge
